### ISSUE TITLE
Runtime error on unload plugin: QGIS 3.36.0-Maidenhead on Ubuntu Linux

### ISSUE THREAD

**Issue by marcobra** [mkoenigb/ProcessX#7]
Hi, with latest plugin update v1.7.1:  

RuntimeError: wrapped C/C++ object of type ProcessXProvider has been deleted 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 545, in unloadPlugin
    plugins[packageName].unload()
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/marco/python/plugins/ProcessX/processx.py", line 60, in unload
    QgsApplication.processingRegistry().removeProvider(self.provider)
RuntimeError: wrapped C/C++ object of type ProcessXProvider has been deleted

Versione Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] 
Versione di QGIS: 3.36.0-Maidenhead Maidenhead, 09951dc0acf 

Thank

**Comment by marcobra** [comment]
Was some related to source code installed one, i've two plugin processx listed in plugins list so deinstalling all and then reinstall latest one solve this.
